Add ProtocolStart and GracefulClose messages
XRPLF/rippled pull request #3839
Opened 2021-05-06 08:12 UTC by gregtatcam

## High Level Overview of Change

Add InboundHandoff class to send HTTP response 
to the outbound peer and instantiate inbound PeerImp
when the response is sent. The peer then waits for
mtSTART_PROTOCOL message from the connected 
outbound peer. When the message is received, the peer starts 
sending the protocol messages. This update ensures that 
the inbound peer is created once the overlay is established,
eliminating the need for doAccept(). In addition it synchronizes 
send/receive protocol messages between the peers on start,
eliminating the need for copying the read buffer into the outbound
peer constructor. 

Add mtGRACEFUL_CLOSE message to differentiate application
and link layer failures. 

### Type of Change

- [x] New feature (non-breaking change which adds functionality)

2021-05-12 20:04 UTC, HowardHinnant requested changes
ripple/overlay/impl/OverlayImpl.cpp needs an additional include to compile in a non-unity build:
```c++
#include <ripple/overlay/impl/InboundHandoff.h>
```

2021-05-12 20:04 UTC, HowardHinnant commented on src/ripple/overlay/impl/InboundHandoff.cpp
> +#include <ripple/overlay/impl/InboundHandoff.h>
Needs additional includes to compile in non-unity build:
```c++
#include <ripple/overlay/Cluster.h>
#include <ripple/overlay/impl/PeerImp.h>
```

2021-05-12 20:06 UTC, HowardHinnant commented on src/ripple/overlay/impl/InboundHandoff.h
> +    virtual ~InboundHandoff() = default;
Suggest adding `override` qualifier to confirm that the base destructor is virtual.

2021-05-12 20:06 UTC, HowardHinnant commented on src/ripple/overlay/impl/InboundHandoff.h
> +
Recommend adding:
```c++
   InboundHandoff(InboundHandoff const&) = delete;
   InboundHandoff& operator=(InboundHandoff const&) = delete;
 ```
To confirm and document that this class isn't meant to be copied.

2021-05-17 13:45 UTC, HowardHinnant approved these changes

2022-11-28 19:26 UTC, intelliot commented
(notes: changes how servers communicate with each other; Nik will review later)

2023-02-08 06:15 UTC, intelliot commented
@nbougalis you previously planned to review this; is that still the case?

2023-07-20 05:58 UTC, intelliot commented
@gregtatcam do you think this PR still makes sense to merge in?

2023-07-24 19:12 UTC, gregtatcam commented
> @gregtatcam do you think this PR still makes sense to merge in?

@nbougalis thought it was a useful enhancement. I don't have a strong opinion one way or another. There is certainly a risk since we are changing how the protocol starts/shuts down. This sequence had not changed in a very long time.

2023-07-27 15:40 UTC, ckeshava commented
Apologies for the delay in my review. I had a few clarifying questions and I have posted the same.

I don't understand the limitations of the `doAccept()` function. Why are we trying to replace it? I get the performance benefits of the buffer-copy, but that seems to occur only at the beginning of the handshake right?

2023-07-27 18:43 UTC, gregtatcam commented on src/ripple/overlay/Message.h
> +    getType() const;
It's `private` in the latest `develop` branch.

2023-07-27 18:43 UTC, gregtatcam commented on src/ripple/overlay/impl/Message.cpp
> +    int type =
`setHeader()` comments:
>    All multi-byte values are represented in big endian.

    For uncompressed messages (6 bytes), numbering bits from left to right:

        - The first 6 bits are set to 0.
        - The next 26 bits represent the payload size.
        - The remaining 16 bits represent the message type.

    For compressed messages (10 bytes), numbering bits from left to right:

        - The first 32 bits, together, represent the compression algorithm
          and payload size:
            - The first bit is set to 1 to indicate the message is compressed.
            - The next 3 bits indicate the compression algorithm.
            - The next 2 bits are reserved at this time and set to 0.
            - The remaining 26 bits represent the payload size.
        - The next 16 bits represent the message type.
        - The remaining 32 bits are the uncompressed message size.
and this is how it's set 
>   *in++ = static_cast<std::uint8_t>((type >> 8) & 0xFF);
    *in++ = static_cast<std::uint8_t>(type & 0xFF);

2023-07-27 22:25 UTC, ckeshava commented on src/ripple/overlay/impl/Message.cpp
> +    int type =
ok, thanks for the explanation.

2023-07-27 22:27 UTC, ckeshava commented on src/ripple/overlay/Message.h
> +    getType() const;
yes, I was referring to this feature branch. It is `public` in this branch, I'm wondering why it differs from the develop branch ?

2023-07-27 22:29 UTC, gregtatcam commented on src/ripple/overlay/Message.h
> +    getType() const;
To your point - it should had not be `public`. So it got fixed a while back.

2023-07-31 12:30 UTC, ckeshava commented on src/ripple/overlay/Message.h
> +    getType() const;
okay, thanks for the clarification.

2023-07-31 14:55 UTC, gregtatcam commented
> Apologies for the delay in my review. I had a few clarifying questions and I have posted the same.
> 
> I don't understand the limitations of the `doAccept()` function. Why are we trying to replace it? I get the performance benefits of the buffer-copy, but that seems to occur only at the beginning of the handshake right?

It's not that `doAccept()` has limitation but the flow is not correct. At a super high level, this is how the overlay connection is established prior to this fix. 

The outbound connection (client) is handled by `ConnectAttempt`. `ConnectAttempt` sends the handshake once the connection is established. The handshake response is processed by `ConnectAttempt::processResponse()`, which verifies the handshake, instantiates outbound `PeerImp`, and adds it to `OverlayImpl` list of active peers (`OverlayImpl::add_active()`). This in turns runs the peer (`PeerImp::run()`) and for the outbound peer it starts the protocol (`doProtocolStart()`). The outbound peer is ready to process protocol messages at this point.

There is a lot more going on for the inbound connection. But ultimately it is handled by `OverlayImpl::onHandoff()`. `onHandoff()` verifies the handshake, instantiates the inbound peer, adds it to its list (not via `add_active()`), and runs the peer (`PeerImp::run()`). `run()` calls `doAccept()` for the inbound peer, which sends the handshake response, and then starts the protocol (`doProtocolStart()`). The inbound peer is ready to process protocol messages at this point. 

This flow sort of looks fine, but the problem is that the inbound peer is added to the overlay active list before the peer is ready to process the protocol messages; i.e. it has to send the handshake response first. This PR fixes this issue by adding `InboundHandoff` class, which is instantiated in `OverlayImpl::onHandoff()` instead of instantiating `PeerImp`. `InboundHandoff::sendResponse()` sends the handshake response. Once the response is written, `InboundHandoff` instantiates inbound `PeerImp` and adds it to `OverlayImpl` list of active peers (`OverlayImpl::add_active()`). Note how both inbound and outbound peer are added now consistently to the overlay active list via `add_active()`. This in turns runs the peer (`PeerImp::run()`) and starts the protocol (`doProtocolStart()`).  Again, this is handled consistently for both types of peers. Both inbound and outbound peers are active at this point. There is one more thing that needs to happen though. The inbound peer sent the response to the outbound peer but the inbound peer doesn't really know at this point if the outbound peer is ready. To kick start this process, the outbound peer sends `mtSTART_PROTOCOL` protocol message. Once the inbound peer receives this message, it starts sending the protocol messages. Everything is copacetic between the peers now.

This PR also adds `mtGRACEFUL_CLOSE` message to gracefully close the protocol whenever possible instead of just blindly closing the connection.

I have not looked at this code for two years so might have missed something...

2023-07-31 16:13 UTC, ckeshava commented
thank you so much Greg, this explanation gave a lot of context to the PR change. 

In the current codebase, is it possible to have "phantom" peers? Since the inbound peer is added to the Overlay active peers list before receiving the handshake response, what is the fallback mechanism if we have incorrectly added a peer?

2023-07-31 16:19 UTC, gregtatcam commented
> thank you so much Greg, this explanation gave a lot of context to the PR change.
> 
> In the current codebase, is it possible to have "phantom" peers? Since the inbound peer is added to the Overlay active peers list before receiving the handshake response, what is the fallback mechanism if we have incorrectly added a peer?

I don't think there is a fallback mechanism for this scenario.

2023-09-03 22:08 UTC, intelliot commented
@ckeshava - what are your thoughts on this PR? Is it worth merging, or should it just be closed without merging?

2023-09-05 17:49 UTC, ckeshava approved these changes

2023-09-05 17:50 UTC, ckeshava commented
I think this PR should be merged 👍

2023-09-22 06:19 UTC, intelliot commented
@JoelKatz FYI - since this is an area of the code that hasn't been touched in many years, let me know if there is anything that needs to be further tested.

@sophiax851 it would be useful to confirm that none of these changes have adverse performance impact. Thank you!

2023-09-22 22:55 UTC, intelliot commented
Thank you! This will be included in the next beta. If we find any issues with it, we can revert it as appropriate.

2023-09-22 22:56 UTC, merged

2023-09-25 21:46 UTC, intelliot commented
note: we should check with @nbougalis on whether this should be kept in