Compile rippled with "-pie"
XRPLF/rippled pull request #4082
Opened 2022-01-25 23:09 UTC by legleux

## High Level Overview of Change
Add gcc position independent executable flag for added binary hardening.

### Context of Change

### Type of Change

- [x] New feature (non-breaking change which adds functionality)

2022-01-25 23:26 UTC, legleux commented
Looks like this may need `-pie` added to the linker invocation so this isn't quite done.
[Slew of CMake issues discussing PIE](https://gitlab.kitware.com/cmake/cmake/-/issues/14983)
[Can manually do it](https://mropert.github.io/2018/02/02/pic_pie_sanitizers/#:~:text=final%20executable%20to%20add%20%2Dpie%20by%20hand%20using%20CMAKE_EXE_LINKER_FLAGS)

2022-02-11 17:27 UTC, thejohnfreeman requested changes
Leaving it to policy CMP0083 requires CMake 3.14, but we only require at least 3.9. I don't think we want to bump that requirement just for this feature so two options:

- If everything will still link successfully, but perhaps position dependently, with CMake <3.14, then I can approve as-is.
- If this will not link successfully because of the missing flag when using CMake <3.14, then we need to either add the flag manually (my preference) or revert these changes.

2022-02-26 04:00 UTC, legleux commented
Hmm, rippled doesn't build with CMake 3.9 anymore because of the updated rocksdb version.
Let's just bump the minimum as high as we date.

2022-04-27 14:02 UTC, thejohnfreeman requested changes

2022-04-27 14:02 UTC, thejohnfreeman commented on Builds/CMake/RippledCore.cmake
> +
If #4109 goes in, this block should be reduced to just lines 11 and 12.

2022-06-29 15:01 UTC, thejohnfreeman approved these changes

2022-11-28 19:54 UTC, intelliot commented
(notes: would be good to merge)

@RichardAH does this interfere with any work you're doing with Hooks or any other project?

2023-03-16 02:51 UTC, legleux commented
Almost none of these files even exist anymore

2023-03-16 02:51 UTC, closed without merging