Improve detection & handling of duplicate Node ID:
XRPLF/rippled pull request #4195
Opened 2022-06-04 01:47 UTC by nbougalis

Each node on the network is supposed to have a unique cryptographic identity. Typically, this identity is generated randomly at startup and stored for later reuse in the (poorly named) file `wallet.db`.

If the file is copied, it is possible for two nodes to share the same node identity. This is generally not desirable and existing servers will detect and reject connections to other servers that have the same key.

This commit achives three things:

1. It improves the detection code to pinpoint instances where two distinct servers with the same key connect with each other. In that case, servers will log an appropriate error and shut down pending intervention by the server's operator.
2. It makes it possible for server administrators to securely and easily generate new cryptographic identities for servers using the new `--newnodeid` command line arguments. When a server is started using this command, it will generate and save a random secure identity.
3. It makes it possible to configure the identity using a command line option, which makes it possible to derive it from data or parameters associated with the container or hardware where the instance is running by passing the `--nodeid` option, followed by a single argument identifying the infomation from which the node's identity is derived. For example, the following command will result in nodes with different hostnames having different node identities: `rippled --nodeid $HOSTNAME`

The last option is particularly useful for automated cloud-based deployments that minimize the need for storing state.

The commit also updates the minimum supported server protocol version to `XRPL/2.1`, which has been supported since version 1.5.0 and eliminates support for `XPRL/2.0`.

## High Level Overview of Change

### Context of Change

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

2022-06-10 17:58 UTC, HowardHinnant requested changes
I'm getting 3 test failures:
```
$ rippled --unittest=ProtocolVersion
ripple.overlay.ProtocolVersion Convert protocol version to string
ripple.overlay.ProtocolVersion Convert strings to protocol versions
ripple.overlay.ProtocolVersion Protocol version negotiation
#2 failed: ProtocolVersion_test.cpp(85)
#3 failed: ProtocolVersion_test.cpp(87)
#4 failed: ProtocolVersion_test.cpp(90)
105ms, 1 suite, 3 cases, 15 tests total, 3 failures
```

2022-06-13 19:35 UTC, nbougalis commented
> I'm getting 3 test failures:
> 
> ```
> $ rippled --unittest=ProtocolVersion
> ripple.overlay.ProtocolVersion Convert protocol version to string
> ripple.overlay.ProtocolVersion Convert strings to protocol versions
> ripple.overlay.ProtocolVersion Protocol version negotiation
> #2 failed: ProtocolVersion_test.cpp(85)
> #3 failed: ProtocolVersion_test.cpp(87)
> #4 failed: ProtocolVersion_test.cpp(90)
> 105ms, 1 suite, 3 cases, 15 tests total, 3 failures
> ```

Weird... I'll look into it.

2022-06-14 18:32 UTC, nbougalis commented
Fixed: the unit test was expecting support for obsolete protocol version 2.0 which this commit removed support for.

2022-06-14 20:27 UTC, HowardHinnant commented
The test failures I'm now seeing have slightly changed:
```
ripple.overlay.ProtocolVersion Convert strings to protocol versions
#2 failed: ProtocolVersion_test.cpp(45)
#4 failed: ProtocolVersion_test.cpp(45)
#5 failed: ProtocolVersion_test.cpp(45)
```

2022-07-01 19:41 UTC, HowardHinnant approved these changes

2022-07-11 15:26 UTC, thejohnfreeman approved these changes

2022-08-26 20:00 UTC, closed without merging

2025-03-13 15:27 UTC, intelliot commented
NB: reverted by https://github.com/XRPLF/rippled/pull/4438