Update CONTRIBUTING.md to add enhanced rules
XRPLF/rippled pull request #4232
Opened 2022-07-12 09:15 UTC by RichardAH

## High Level Overview of Change

Further to discussions on the XRPLF Mattermost `~XRPL Technical` channel. Further additions / changes welcome in the discussion to this PR and will be added here to avoid too many commits about the same thing.

2022-07-12 20:09 UTC, ximinez requested changes

2022-07-12 21:08 UTC, RichardAH commented on CONTRIBUTING.md
> +1. All commits must be _signed_ using an appropriately set key, such that GitHub marks the commit as `verified`. Please see [Signing Commits](https://docs.github.com/en/authentication/managing-commit
I agree with you. Is there any significant disadvantage to always requiring signed commits however?

2022-07-12 21:09 UTC, RichardAH commented on CONTRIBUTING.md
> +3. When asked by a reviewer to fix something in your PR you should force push a rebase on your branch to replace previous bad commits with good commits while your PR is open.
Can you rewrite this section how you’d like to see it

2022-07-14 14:57 UTC, wojake commented on CONTRIBUTING.md
> +1. All commits must be _signed_ using an appropriately set key, such that GitHub marks the commit as `verified`. Please see [Signing Commits](https://docs.github.com/en/authentication/managing-commit
There's no real downside to it especially for a project like `rippled`. I suppose it's just a hassle to remind yourself to sign *every* commit, it's not necessary but it's a safety precaution. All critical/important commits should be signed IMO.

2022-07-14 15:01 UTC, cjcobb23 commented on CONTRIBUTING.md
> +1. All commits must be _signed_ using an appropriately set key, such that GitHub marks the commit as `verified`. Please see [Signing Commits](https://docs.github.com/en/authentication/managing-commit
you can configure git to sign every commit by default. I don't think it adds any overhead, once you already have signing set up

2022-07-14 15:14 UTC, cjcobb23 commented on CONTRIBUTING.md
> +3. When asked by a reviewer to fix something in your PR you should force push a rebase on your branch to replace previous bad commits with good commits while your PR is open.
I also prefer fold commits as a reviewer, so I can see what has changed since the last time I reviewed

2022-07-16 02:13 UTC, thejohnfreeman commented on CONTRIBUTING.md
> +1. All commits must be _signed_ using an appropriately set key, such that GitHub marks the commit as `verified`. Please see [Signing Commits](https://docs.github.com/en/authentication/managing-commit
It's a barrier to entry that is unnecessary. Most existing contributors are not signing their commits.

2022-07-16 02:22 UTC, thejohnfreeman commented on CONTRIBUTING.md
> +4. If the `develop` branch moves forward without your PR being merged, it is your responsibility to keep it *fully up to date and merge-compatible* with the develop branch. If this is not done in a t
What is timely? Perhaps we should lay out some fixed deadlines.

Should this policy extend to PRs that become stale while unmergeable for other reasons, e.g. unaddressed comments and requests for changes, or failed tests?

2022-07-17 06:03 UTC, RichardAH commented
Someone else can rewrite it and open a new PR

2022-07-17 06:03 UTC, closed without merging