Fix for issue 3298
XRPLF/rippled pull request #4240
Opened 2022-07-15 23:28 UTC by chennakeshava1998

If merged, this commit will:
- Provide comparative analysis of Data Structures
- time/profile performance of parseCommand function
- declare commands array as constexpr

2022-07-15 23:28 UTC, chennakeshava1998 commented
@scottschurr  @nbougalis  let me know if this looks okay.

2022-07-16 00:17 UTC, nbougalis requested changes
Thank you for doing this, but I think that the inline comment is not necessary.

Instead, what I recommend, is that you change this commit to simply remove the `FIXME` comment and provide a description of the tests you performed in the commit (i.e. what you have as a comment) as part of the commit message.

2022-07-19 21:54 UTC, chennakeshava1998 commented
> 

Okay, I have done the suggested changes 👍

2022-07-25 21:40 UTC, intelliot approved these changes

2022-08-26 20:00 UTC, closed without merging