Use constexpr to check memo validity
XRPLF/rippled pull request #4249
Opened 2022-07-24 20:02 UTC by cryptobrad

## High Level Overview of Change

### Context of Change

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

2022-07-27 01:02 UTC, scottschurr requested changes
Good call making that `array` `constexpr`.  Nicely done.  :+1:

That said, I have four changes I'd like to suggest.

Three of those changes are specifically in the code you modified.  If you want you can cherry-pick those change here: https://github.com/scottschurr/rippled/commit/a6fcecf788c09c9cc8c0f2a7175ad62883537aea  Also feel free to make the changes yourself if you prefer.

There's also a fourth change that should be made.  I looked at the code coverage associated with your changes and noticed our current tests miss your changes all together.  Not your fault!  That was a pre-existing condition.

Nevertheless, since the code is being modified, it really ought to be exercised by the unit tests.  So I cobbled together a small test that exercises your changes and a few other invalid `memo` conditions that were previously not exercised.  A commit with those tests is here: https://github.com/scottschurr/rippled/commit/242368610ae76d0ee12277d8f1d275d142cd443f

You should feel free to cherry-pick that commit.  Or, if you prefer, you can write your own test.

Thanks for your submission!

2022-07-27 22:58 UTC, nbougalis commented on src/ripple/protocol/impl/STTx.cpp
> +static constexpr std::array<char, 256> const allowedSymbols = []() {
Agreed - this should stay within the `isMemoOkay` function to limit its scope as much as possible.

2022-07-27 23:01 UTC, nbougalis commented on src/ripple/protocol/impl/STTx.cpp
> +        a[c] = c;
This is a good point. When first looking at this, I noticed this change but didn't think much of it. I would have missed this.

Thank you @scottschurr; your comment makes clear why using `a[c] = c` is problem: it makes the `\0` character appear to be "valid" when it isn't.

2022-07-29 19:18 UTC, cryptobrad commented
Thanks I have used your fix into my code

2022-08-03 21:06 UTC, scottschurr reviewed
Changes look good!  Thanks for doing this.

That said, I'm a bit uncomfortable that this change is not exercised by the unit tests.  And, yeah, I have to admit that the code being untested is a long-standing problem.  But just because it's a long-standing problem doesn't mean it shouldn't be addressed.  I have two suggestions for how we can approach getting this code tested:

1. You could add tests to this pull request or
2. I could submit a pull request that adds tests for Memo.

I've written such tests, and your code passes them.  You can see those tests here: https://github.com/scottschurr/rippled/commits/memo-test

You're welcome to add those tests (or similar) to this pull request.  Or we can leave this pull request as it is and I'll submit a separate pull request that adds the tests to the code base.  Either way the code base eventually has the same outcome.

Let me know which if those two approaches appeals more to you.  Thanks.

2022-08-04 18:47 UTC, HowardHinnant approved these changes

2022-08-26 20:00 UTC, closed without merging

2023-02-16 06:04 UTC, intelliot commented
> 1. You could add tests to this pull request or
> 2. I could submit a pull request that adds tests for Memo.
> 
> I've written such tests, and your code passes them. You can see those tests here: https://github.com/scottschurr/rippled/commits/memo-test
> 
> You're welcome to add those tests (or similar) to this pull request. Or we can leave this pull request as it is and I'll submit a separate pull request that adds the tests to the code base. Either way the code base eventually has the same outcome.

For posterity: these tests were added by https://github.com/XRPLF/rippled/pull/4287