Remove charUnHex
XRPLF/rippled pull request #4268
Opened 2022-08-09 19:10 UTC by cryptobrad

## High Level Overview of Change

### Context of Change

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

2022-08-11 16:15 UTC, scottschurr requested changes
Thanks for the submission.  This pull request looks pretty close to right, but needs a couple of fixes.  Once those fixes are in place I think this will be good to go.

2022-08-11 16:15 UTC, scottschurr commented on src/ripple/basics/StringUtilities.h
> +    static constexpr std::array<int, 256> const unxtab = []() {
This file now needs a `#include <array>`.  Please add that near the top of the file like this...
```
...
#include <boost/utility/string_view.hpp>
#include <array>
#include <optional>
...
```

2022-08-11 16:15 UTC, scottschurr commented on src/ripple/basics/StringUtilities.h
>          ++iter;
By accident you left in a double increment.  Fortunately it causes massive unit test failures.  Notes:
1. You'll need to remove the `++iter;` from this line.
2. Consider running the unit tests before submitting pull requests in the future.  It's easy.  Build rippled, then invoke...
```
$ <path to rippled> --unittest
```
Then wait for the results.  It takes a while, but if it says `0 failures` at the end then you're less likely to have introduced a bug.

2022-08-16 17:36 UTC, cryptobrad commented
Thanks for looking closely
I fixed the bug you found

2022-08-16 20:04 UTC, scottschurr approved these changes
:+1: Latest version looks good to me!  Thanks.

2022-08-29 23:54 UTC, nbougalis commented
Merged as 83ac141f656b1a95b5661853951ebd95b3ffba99

2022-08-29 23:54 UTC, closed without merging