Allow port numbers be be specified using a either a colon or a space
XRPLF/rippled pull request #4328
Opened 2022-10-24 15:39 UTC by RichardAH

## High Level Overview of Change
An annoying *gotcha* for node operators is accidentally specifying IP:PORT combinations using a colon. Rippled expects a space, not a colon, and for whatever reason does not provide good feedback when this operator error is made.

This small PR simply allows this mistake (colon) to be replaced inline with a space, preserving the intention of the operator.

### Context of Change

### Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Test Plan
* `testColons()` has been added to the config unit tests. This tests the functionality when specifying IP:PORT in rippled.cfg.
* The RPCCall test regime is not specific enough to test this functionality, but I have tested it by hand (and you should too).

2022-10-25 05:05 UTC, nbougalis requested changes

2022-10-25 05:05 UTC, nbougalis commented on src/ripple/net/impl/RPCCall.cpp
> +        }
This logic breaks if you specify an IPv6 address, whether you use brackets or not, and that can be a moderately annoying problem.

Perhaps considering checking if `ip` can be successfully parsed as either an IPv6 addresses using, for example,
[make_address_v6](https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/reference/ip__address_v6/make_address_v6.html) and only doing this is if it isn't.

2022-10-25 09:44 UTC, RichardAH commented
Thanks for the review @nbougalis. After some consideration I decided simply detecting the presence of more than one colon should be sufficient to filter out IPv6 cases. Since IPv6 can be ambiguous if a colon is used for port (in particular if square braces are also not used), IPv6 ports must remain specified via space character.

2022-10-26 06:09 UTC, nbougalis approved these changes
Looks good with the change to detect IPv6 addresses.

I have an idea for a more comprehensive fix (improve Boost's parsers, and use those :laughing:) but this is fine for now.

2022-11-23 22:30 UTC, ximinez requested changes

2022-12-14 00:18 UTC, intelliot commented
@RichardAH when you have a chance, please respond to ximinez's comments above. Thanks!

2023-02-17 19:13 UTC, ximinez approved these changes
I wouldn't mind seeing `develop` merged in to the branch just so CI can get a shot at it, but I don't see a problem if not. Sorry for the delay!

2023-02-23 05:39 UTC, intelliot commented
@RichardAH I merged `develop` into the branch. If you feel this PR is ready to merge, please put the `Passed` label on it.

(do not merge it yet)

2023-03-15 04:06 UTC, merged