Update SECURITY.md
XRPLF/rippled pull request #4338
Opened 2022-11-09 18:01 UTC by intelliot

## High Level Overview of Change

This updates the markdown file that the Bug Bounty Program, which applies to this software (and supported related libraries).

### Context of Change

xrpl.js is the new name for the JavaScript library; xrpl-py and xrpl4j should also be in-scope for this program.

### Type of Change

- [x] Documentation Updates

2022-11-09 22:06 UTC, ckniffen approved these changes

2023-03-21 12:38 UTC, gregtatcam requested changes

2023-03-21 12:38 UTC, gregtatcam commented on SECURITY.md
>  This program allows us to recognize and reward individuals or groups that identify and report bugs. In summary, order to qualify for a bounty, the bug must be:
typo: `order` , should be `in order`.

2023-03-21 12:38 UTC, gregtatcam commented on SECURITY.md
> +[Ripple](https://ripple.com) is generously sponsoring a bug bounty program for vulnerabilities in [`rippled`](https://github.com/XRPLF/rippled) (and other related projects, like [`xrpl.js`](https://g
Why us Ruby client library is not included?

2023-06-09 20:54 UTC, ximinez approved these changes
Looks good.

2023-09-01 22:56 UTC, ckniffen approved these changes

2023-09-08 20:51 UTC, merged