Fix a case where ripple::Expected returned a json array, not a value
XRPLF/rippled pull request #4401
Opened 2023-01-27 17:55 UTC by scottschurr

## High Level Overview of Change

@godexsoft reported a problem with the `ripple::Expected` implementation and provided a proposed fix.  The problem is that there are conditions where `Expected` invokes the wrong constructor for the expected type.  A constructor that takes multiple arguments might be interpreted as an array.

The proposed fix was a minor adjustment to three constructors that replaces the use of curly braces with parens.

A unit test also came along for the ride.

This pull request incorporates the suggested fix and the unit test into the rippled code base.

### Context of Change

Clio is using `ripple::Expected` and had a problem.  This change makes `Expected` useable for Clio.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)

2023-01-29 16:10 UTC, seelabs approved these changes
:+1: LGTM

2023-03-21 19:30 UTC, HowardHinnant approved these changes
Subtle!

2023-03-21 20:33 UTC, HowardHinnant requested changes
I approved too quickly.

Using boost 1.77 I'm getting this link-time error:
```
[ 16%] Linking CXX executable rippled
Undefined symbols for architecture x86_64:
  "boost::json::value::value(boost::json::value&&)", referenced from:
      ripple::test::Expected_test::run()::'lambda9'()::operator()() const in Expected_test.cpp.o
  "boost::json::value::~value()", referenced from:
      ripple::test::Expected_test::run() in Expected_test.cpp.o
      ripple::test::Expected_test::run()::'lambda9'()::operator()() const in Expected_test.cpp.o
  "boost::json::object::object(boost::json::object&&)", referenced from:
      ripple::test::Expected_test::run()::'lambda9'()::operator()() const in Expected_test.cpp.o
  "boost::json::object::object(std::initializer_list<std::__1::pair<boost::basic_string_view<char, std::__1::char_traits<char> >, boost::json::value_ref> >, unsigned long, boost::json::storage_ptr)", referenced from:
      ripple::test::Expected_test::run()::'lambda9'()::operator()() const in Expected_test.cpp.o
  "boost::json::object::~object()", referenced from:
      ripple::test::Expected_test::run()::'lambda9'()::operator()() const in Expected_test.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [rippled] Error 1
make[1]: *** [CMakeFiles/rippled.dir/all] Error 2
make: *** [all] Error 2
```

It appears to be a boost error.  Investigating...

2023-03-21 23:43 UTC, scottschurr commented
I'm using boost 1_75_0 and it's building for me.  I'll be interested to hear what you discover @HowardHinnant.

2023-03-22 20:26 UTC, HowardHinnant approved these changes
I have a new trusted development machine that correctly compiles, links and unittests this! :tada: Sorry for the delay.

2023-03-22 20:53 UTC, scottschurr commented
@HowardHinnant, thanks for being thorough.  Marked as Passed.

2023-03-23 17:34 UTC, intelliot commented
(not blocking on @godexsoft; just tagging for visibility)

2023-03-23 17:36 UTC, godexsoft approved these changes
LGTM 🚀

2023-03-23 17:41 UTC, intelliot commented
Suggested commit message:

```
fix(`Expected`): return a value: (#4401)

Fix a case where `ripple::Expected` returned a json array, not a value.

The problem was that `Expected` invoked the wrong constructor for the
expected type, which resulted in a constructor that took multiple
arguments being interpreted as an array.

A proposed fix was provided by @godexsoft, which involved a minor
adjustment to three constructors that replaces the use of curly braces
with parentheses. This makes `Expected` usable for
[Clio](https://github.com/XRPLF/clio).

A unit test is also included to ensure that the issue doesn't occur
again in the future.
```

2023-03-23 17:50 UTC, ximinez commented
I'm not a fan of this commit message style. I still use https://cbea.ms/git-commit/ as sort of the "git commit message bible".

If the goal is to write shorter subject lines and include the PR number, how about something like:
```
Fix `Expected` to return a value (#4401)
```

2023-03-24 00:32 UTC, merged

2023-03-24 14:26 UTC, ximinez commented
> Given the two suggested commit messages, I feel like the one suggested by @ximinez is a bit too terse. I'm fine with the one suggested by @intelliot however. And I appreciate how both of them managed the line lengths smile

Oh, I should have been clearer - that was just the subject line. The rest of the body was fine.