Refactor and minor optimizations
XRPLF/rippled pull request #4412
Opened 2023-02-07 19:10 UTC by nbougalis

2023-04-20 15:16 UTC, intelliot commented
@nbougalis do you think this is still worth doing?

If so, could you suggest 2-3 potential reviewers?

2023-04-30 20:10 UTC, nbougalis commented
I think there are a lot of good improvements here, both simplifying and cleaning up the code. The review should be relatively straight-forward.

As for reviewers, if you're looking to assign someone from the Ripple team, then: @HowardHinnant and either @ximinez or @thejohnfreeman. I guess it would be nice to have someone else, too. Maybe @nixer89 or @dangell7, if either of them is feeling up to it.

I'll try to fix conflicts tonight.

2023-08-23 20:47 UTC, HowardHinnant requested changes

2023-09-26 17:43 UTC, nbougalis commented on src/ripple/app/ledger/impl/InboundLedger.cpp
> +            (userdata_ & (IL_HAVE_STATE | IL_HAVE_TXNS)))
Hmm... good eyes, there. You may be right, but I will have to think carefully about this before giving you a definitive yes or no.

2023-10-16 05:57 UTC, closed without merging