README: Add a few source code starting points
XRPLF/rippled pull request #4421
Opened 2023-02-14 00:27 UTC by intelliot

## High Level Overview of Change

Replaced some obsolete content with helpful content.

### Context of Change

Travis-CI and Codecov have not been used in a long time.

### Type of Change

- [x] Documentation Updates

2023-02-14 03:19 UTC, justinr1234 approved these changes

2023-02-15 20:30 UTC, thejohnfreeman requested changes

2023-02-15 20:30 UTC, thejohnfreeman commented on README.md
> +Here some good places to start learning the source code:
```suggestion
Here are some good places to start learning the source code:
```

2023-02-16 10:16 UTC, drlongle approved these changes

2023-02-18 06:27 UTC, merged