Set version to 1.10.0
XRPLF/rippled pull request #4451
Opened 2023-03-07 16:32 UTC by intelliot

## High Level Overview of Change

The version number is updated to 1.10.0 for the stable release. Release notes are included.

### Context of Change

No release blockers have been identified in 1.10.0-rc4, so this is the same as rc4.

### Type of Change

- [x] Release

2023-03-07 18:00 UTC, intelliot commented
Flaky test:
```
1> ripple.app.AccountSet WalletID
0> #157 failed: apply: Got temINVALID (The transaction is ill-formed.); Expected tesSUCCESS (The transaction was applied. Only final in a validated ledger.)
0> {
   "Account" : "raMjuzZYRZ4yza9DAd5Szt9tz9ZDzD4QzP",
   "Amount" : {
      "currency" : "XAU",
      "issuer" : "rExKpRKXNz25UAjbckCRtQsJFcSfjL9Er3",
      "value" : "1000"
   },
   "Destination" : "rExKpRKXNz25UAjbckCRtQsJFcSfjL9Er3",
   "Fee" : "10",
   "Flags" : 2147483648,
   "Sequence" : 13,
   "SigningPubKey" : "023F321AFD65B713B5394BBE2C9EE07218985DEDC56C53DE9F89749F9DF56A70ED",
   "TransactionType" : "Payment",
   "TxnSignature" : "3045022100A8B4E6EC2D181BF7DFFB7A7983EE426E5E812C0252324471AC23E489F602282D02200B2C68308DAD156B8618B99AEBBAC79BDDA6F5AEF8AA9C173646BA0D9208F537"
}

1> ripple.app.AccountSet EmailHash
```

2023-03-07 20:16 UTC, intelliot commented
Due to an unexplainable LogicError seen on a Testnet client handler, and a desire to run 1.10.0-rc4 on more servers as a burn-in period, the maintainers have decided to push the target release date out by 1 week to: Tuesday, March 14, 2023.

1.10.0-rc4 continues to have no known issues, and the maintainers recommend deploying it for testing purposes. If any issues are detected, please report them here. Security-sensitive issues should be reported to bugs@xrpl.org.

2023-03-08 06:19 UTC, legleux requested changes

2023-03-08 06:19 UTC, legleux commented on RELEASENOTES.md
> +- **Use the Conan package manager**: Added a `conanfile.py` and Conan recipe for RocksDB to enable building dependencies with Conan. [#4367](https://github.com/XRPLF/rippled/pull/4367)
RocksDB recipe was removed as it's in ConanCenter now.
One for Snappy was added. https://github.com/XRPLF/rippled/commit/c2b03fecca19a304b37467b01fa78593d3dce3fb)

2023-03-08 17:38 UTC, nbougalis commented
> Due to an unexplainable LogicError seen on a Testnet client handler, and a desire to run 1.10.0-rc4 on more servers as a burn-in period, the maintainers have decided to push the target release date out by 1 week to: Tuesday, March 14, 2023.
> 
> 1.10.0-rc4 continues to have no known issues, and the maintainers recommend deploying it for testing purposes. If any issues are detected, please report them here. Security-sensitive issues should be reported to [bugs@xrpl.org](mailto:bugs@xrpl.org).

What is the `LogicError`?

2023-03-08 18:52 UTC, intelliot commented
@nbougalis: emailed to you

2023-03-08 18:54 UTC, intelliot commented on RELEASENOTES.md
> +- **Use the Conan package manager**: Added a `conanfile.py` and Conan recipe for RocksDB to enable building dependencies with Conan. [#4367](https://github.com/XRPLF/rippled/pull/4367)
```suggestion
- **Use the Conan package manager**: Added a `conanfile.py` to enable building dependencies with Conan [#4367](https://github.com/XRPLF/rippled/pull/4367). A recipe for Snappy was added [c2b03fe](https://github.com/XRPLF/rippled/commit/c2b03fecca19a304b37467b01fa78593d3dce3fb)
```

2023-03-14 16:27 UTC, manojsdoshi approved these changes
LGTM

2023-03-14 16:30 UTC, merged