Improve checking of the path lengths during Payments
XRPLF/rippled pull request #4519
Opened 2023-05-07 20:41 UTC by a-noni-mousse

## High Level Overview of Change

The code that does the check of the payment path lengths was sometimes executed but without an effect so change it to only  work when it matters and to not make not necessary copies of the path vectors.

### Context of Change

The code checks size of payment path lengths but it is only pertinente when executing again open view and doing the work when not open.
This is only start I think there are also other issue with the paths codes that need to be fixed.

### Type of Change

- [X] Refactor (non-breaking change that only restructures code)

## Test Plan

Do the unit tests.

2023-05-10 23:52 UTC, nbougalis requested changes
One bug needs to be addressed; once it is, this gets a :+1: from me. Nice find.

2023-05-10 23:52 UTC, nbougalis commented on src/ripple/app/tx/impl/Payment.cpp
> +                return path.size() > MaxPathSize;
Bug: the check against individual paths should compare against `MaxPathLength` here.

2023-05-11 21:45 UTC, nbougalis approved these changes

2023-08-10 15:11 UTC, gregtatcam approved these changes
👍 LGTM

2023-08-14 21:04 UTC, intelliot commented
Suggested commit message:
```
refactor: improve checking of path lengths (#4519)

Improve the checking of the path lengths during Payments. Previously,
the code that did the check of the payment path lengths was sometimes
executed, but without any effect. This changes it to only check when it
matters, and to not make unnecessary copies of the path vectors.
```

@a-noni-mousse - please confirm (1) that this PR is ready to merge, in your opinion, and (2) the above commit message looks good (for the squashed commit when this PR is merged). Alternatively, you can suggest a different commit message.

2023-08-16 16:45 UTC, intelliot commented
@manojsdoshi to consider for the next beta - please squash and use the commit message [above](https://github.com/XRPLF/rippled/pull/4519#issuecomment-1678058728)

2023-08-23 19:34 UTC, closed without merging