fix node size estimation
XRPLF/rippled pull request #4536
Opened 2023-05-24 15:39 UTC by dangell7

## High Level Overview of Change

This patch fixes a bug in the NODE_SIZE autodetection feature in the Config.cpp file. Specifically, this patch corrects the calculation for the total amount of RAM available, which was previously returned in bytes, but is now being returned in units of the system's memory unit. Additionally, the patch adjusts the node size based on the number of available hardware threads of execution.

### Context of Change

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

2023-05-28 22:02 UTC, nbougalis requested changes
Looks good modulo the one minor change I listed. Once that's done, this gets a :+1: from me.

2023-05-28 22:02 UTC, nbougalis commented on src/ripple/core/impl/Config.cpp
> +            NODE_SIZE = std::min<std::size_t>(hc / 2, 4);
I think you want to replace the `4` with `NODE_SIZE` here.

2023-06-01 22:44 UTC, nbougalis approved these changes

2023-06-06 01:27 UTC, nbougalis commented
This should be included in the next release, as it fixes a bug.

2023-06-06 05:34 UTC, intelliot commented
@manojsdoshi to confirm whether this is ok to include in 1.11

Standard procedure is to get 2 approvals, unless the PR is obviously trivial (and in that case, it needs the `Trivial` label applied). Can you recommend another reviewer?

2023-06-06 05:35 UTC, intelliot commented
Perhaps @sophiax851 or @ChronusZ can take a look?

2023-06-06 15:28 UTC, nbougalis commented
This is a bug fix that impacts servers and, imo, is pretty trivial. Maybe @HowardHinnant can take a quick look?

2023-06-08 18:56 UTC, intelliot commented
QA confirmed this is ok to include in 1.11 (if approved by code review)

2023-06-09 15:59 UTC, HowardHinnant approved these changes
Looks good to me.

Disclaimer:  Part of this change is on a Linux-only branch which I'm not able to test.  However I know @nbougalis is using Linux and he's approved, so I think we're covered.

2023-06-09 16:37 UTC, merged

2023-06-20 23:58 UTC, intelliot commented
Note: This was an older bug (i.e. not a bug introduced in 1.11 nor in an RC - release candidate). It's okay this time, but in the future, QA would like to avoid making non-critical (non-blocker) changes within 2 weeks of a release.