feat: add user version of `feature` RPC
XRPLF/rippled pull request #4781
Opened 2023-10-23 15:34 UTC by mvadari

## High Level Overview of Change

This PR modifies the `feature` RPC to have a non-admin mode that allows conversion from the hex encodings of amendments to human-readable strings.

Example:
```
> {
    "command": "feature",
    "feature": "2E2FB9CF8A44EB80F4694D38AADAE9B8B7ADAFD2F092E10068E61C98C4F092B0"
  }
< {
    "result": {
      "2E2FB9CF8A44EB80F4694D38AADAE9B8B7ADAFD2F092E10068E61C98C4F092B0": {
        "enabled": false,
        "name": "fixUniversalNumber",
        "supported": true
      }
    },
    "type": "response"
  }
```

### Context of Change

This has been requested by many explorer operators, so that the on-ledger hex amendment names can be decoded.

### Type of Change

- [x] New feature (non-breaking change which adds functionality)

### API Impact

- [x] Public API: New feature (new methods and/or new fields)

## Test Plan
Added tests to handle this case.

2023-10-23 17:09 UTC, JST5000 commented
As an additional note, this is a feature I tried to find when I had when trying to set up our docker container for CI since the `Amendments` stanza to force-enable amendments is really hard to read without the human-readable versions of amendments.

2023-10-23 17:26 UTC, dangell7 commented
This seems overkill.

```python
import hashlib

def hash_string(k: str) -> str:
    return hashlib.sha512(k.encode('utf-8')).hexdigest().upper()[:64]
```

```typescript
import * as crypto from 'crypto';

function sha512Hash(k: string): string {
  return crypto.createHash('sha512').update(k, 'utf8').digest('hex').toUpperCase().substring(0, 64);
}
```

2023-10-23 17:28 UTC, mvadari commented
> This seems overkill.

This works for going from the name to the hex, but not the other way around, since you can't reverse a hash.

2023-10-23 18:16 UTC, pkcs8 commented
Would the non-admin version of this command have similar response shape as the admin version? I.e., if I skip the `feature` property, and just send `{"command":"feature"}`, it should return a map of all amendments known to this rippled sans voting data.

2023-10-23 18:19 UTC, mvadari commented
> Would the non-admin version of this command have similar response shape as the admin version? I.e., if I skip the `feature` property, and just send `{"command":"feature"}`, it should return a map of all amendments known to this rippled sans voting data.

I didn't add that here because it's a bit harder to do. But if that's a need, I can add it.

2023-10-23 18:41 UTC, pkcs8 commented
I read rippled websocket url from the environment, and often switch and use admin and non-admin ports interchangeably. I'm not sure  now complicated it would be, but would be great if response shape remains same so I don't have to write conditions. I like how `account_objects` command works with its `type` filter.

2023-10-24 03:58 UTC, lathanbritz commented
> I didn't add that here because it's a bit 

I'm actually a +1 for this I need a way to figure the list of amendments on the network. Currently using external API for mainnet or hardcoded. Would help a lot.

2023-10-24 17:31 UTC, mvadari commented
@pkcs8 @lathanbritz I have switched to the existing admin feature format (removing the admin fields of course) and added the ability to get a list of all features in https://github.com/XRPLF/rippled/pull/4781/commits/43a1ce7b1516b93d3abbf034050afa27c641c956.

2023-10-24 17:36 UTC, mvadari commented
@intelliot can I add @ximinez and @thejohnfreeman as reviewers (if they're okay with that)?

2023-10-24 20:47 UTC, intelliot commented
@mvadari I requested ximinez and thejohnfreeman but the PRs listed here are higher priority: https://github.com/XRPLF/rippled/milestone/8 <- these are 2.0 release blockers

This PR (#4781) is currently planned for 2.1.0

2023-10-31 12:25 UTC, dangell7 commented
We don't like this on `feature` endpoint. We believe opening up feature like this is dangerous. We have opted to move this to the ServerDefinitions.cpp file.

What are your thoughts on this?

I know this goes against what XRPScan asked for but in our opinion its a "safer" solution.

2023-10-31 19:13 UTC, mvadari commented
> We don't like this on `feature` endpoint. We believe opening up feature like this is dangerous. We have opted to move this to the ServerDefinitions.cpp file.
> 
> What are your thoughts on this?
> 
> I know this goes against what XRPScan asked for but in our opinion its a "safer" solution.

This code change is pretty small and therefore easy to audit and test from a security perspective. There is also prior art for functions that have separate user versions and admin versions, like `server_info`, and there have been no issues with those. I'm personally not concerned, but there's also a reason we go through code review 🙂

2023-11-20 22:13 UTC, ximinez requested changes

2023-11-20 22:13 UTC, ximinez commented on src/ripple/rpc/handlers/Feature1.cpp
> +                    t.time_since_epoch().count();
I wouldn't think `majority` time is sensitive information either.

2023-11-20 22:13 UTC, ximinez commented on src/ripple/rpc/handlers/Feature1.cpp
>          if (context.params[jss::vetoed].asBool())
You could make this a lot safer and easier to reason about by simply moving the `isAdmin` check inside the voting block.
```
    if (context.params.isMember(jss::vetoed))
    {
        if (!isAdmin)
            return rpcError(rpcNO_PERMISSION);

        if (context.params[jss::vetoed].asBool())
            table.veto(feature);
        else
            table.unVeto(feature);
    }
```

So now the "voting" code is all in one block, and the logic is like
1. Am I trying to vote?
   1. Am I *allowed* to vote?
      1. No? Fail!
      2. Yes? Vote!

2023-11-20 22:13 UTC, ximinez commented on src/ripple/rpc/handlers/Feature1.cpp
If you changing the `majority` check above, change it here, too.

2023-11-21 20:07 UTC, mvadari commented on src/ripple/app/misc/impl/AmendmentTable.cpp
> +    if (!fs.enabled && lastVote_ && isAdmin)
That's what I was concerned about.

2023-11-29 23:59 UTC, ximinez commented on src/ripple/app/misc/impl/AmendmentTable.cpp
> +    if (!fs.enabled && lastVote_ && isAdmin)
In that case, better safe than sorry.

2023-11-30 02:29 UTC, ximinez approved these changes
Looks good and useful

2023-12-08 19:56 UTC, thejohnfreeman approved these changes

2024-02-01 17:36 UTC, intelliot commented
`Perf Test Desired (Optional)`: This is a new feature in the API, but the perf impact should be negligible.

Internal tracker: RPFC-109

2024-02-01 17:37 UTC, intelliot commented
I think this can be merged once the (trivial) merge conflicts are resolved

2024-02-01 18:18 UTC, mvadari commented
@intelliot merge conflicts have been resolved and I believe this is ready to be merged.

2024-02-01 20:02 UTC, mvadari commented
The coverage check failed to upload, but I don't have permissions to re-run it.

2024-02-02 00:56 UTC, intelliot commented
@ximinez or @Bronek or @mvadari - could you have a quick look to see if the "2 lines in your changes are missing coverage" would be easy to address?

I'm ok to merge as-is if that's what y'all want, but let's confirm that's what we want to do (rather than adding some coverage first)

2024-02-02 18:03 UTC, Bronek commented
> @ximinez or @Bronek or @mvadari - could you have a quick look to see if the "2 lines in your changes are missing coverage" would be easy to address?
> 
> I'm ok to merge as-is if that's what y'all want, but let's confirm that's what we want to do (rather than adding some coverage first)

This is referring lines 917 and 926 of `AmendmentTable.cpp`. There's a newly added `isAdmin` parameter which is used in branching instructions in these lines. Looking at `AmendmentTable_test.cpp` this parameter seem to be only set to `true`, but I do not know about other tests. I think it should be easy to add unit tests to cover `isAdmin=false`, too.

2024-02-05 13:58 UTC, Bronek commented
> > @ximinez or @Bronek or @mvadari - could you have a quick look to see if the "2 lines in your changes are missing coverage" would be easy to address?
> > I'm ok to merge as-is if that's what y'all want, but let's confirm that's what we want to do (rather than adding some coverage first)
> 
> This is referring lines 917 and 926 of `AmendmentTable.cpp`. There's a newly added `isAdmin` parameter which is used in branching instructions in these lines. Looking at `AmendmentTable_test.cpp` this parameter seem to be only set to `true`, but I do not know about other tests. I think it should be easy to add unit tests to cover `isAdmin=false`, too.

I looked at test coverage report of the `develop` branch and see similar partial branch coverage remarks 
![image](https://github.com/XRPLF/rippled/assets/823856/30912966-4ea2-445e-80db-2b937cb22bfd)

at [codecov.io](https://app.codecov.io/gh/XRPLF/rippled/blob/develop/src%2Fripple%2Fapp%2Fmisc%2Fimpl%2FAmendmentTable.cpp)

This makes me thing that the coverage warning is not new actually, and also that it refers to `fs.enabled` and not `isAdmin`.

2024-02-05 16:21 UTC, intelliot commented
- @mvadari to confirm whether she thinks, given the above, this is still ready to be merged now

2024-02-06 20:02 UTC, mvadari commented
> @mvadari to confirm whether she thinks, given the above, this is still ready to be merged now

I checked the tests and I'm pretty sure both branches of `isAdmin` are already checked.

2024-02-07 04:14 UTC, intelliot commented
> (cc @Bronek to double check since he's already taken a look at some of the code)

2024-02-07 16:12 UTC, Bronek requested changes
I recommend adding something as simple as 

```
--- a/src/test/app/AmendmentTable_test.cpp
+++ b/src/test/app/AmendmentTable_test.cpp
@@ -638,6 +638,20 @@ public:
         BEAST_EXPECT(enabled.empty());
         BEAST_EXPECT(majority.empty());

+        uint256 const unsupportedID = amendmentId(unsupported_[0]);
+        {
+            Json::Value const unsupp =
+                table->getJson(unsupportedID, false)[to_string(unsupportedID)];
+            BEAST_EXPECT(unsupp.size() == 0);
+        }
+
+        table->veto(unsupportedID);
+        {
+            Json::Value const unsupp =
+                table->getJson(unsupportedID, false)[to_string(unsupportedID)];
+            BEAST_EXPECT(!unsupp[jss::vetoed].asBool());
+        }
+
         votes.emplace_back(testAmendment, validators.size());

         doRound(
```

This will cover the one missing test case for `isAdmin=false` _after_ we have voted; the other missing branches are around `fs.enabled` and are unrelated to this PR, and so should be ignored here.

2024-02-07 16:12 UTC, Bronek commented on src/ripple/app/misc/impl/AmendmentTable.cpp
> +    if (!fs.enabled && lastVote_ && isAdmin)
You are missing case case for `lastVote_=true` and `isAdmin=false`

2024-02-07 16:17 UTC, Bronek commented
> > (cc @Bronek to double check since he's already taken a look at some of the code)

Thank you @intelliot ; I looked some more and there is one thing that can be improved in unit tests; added it in my feedback.

I use `cmake -Dcoverage-format=json-detail -Dcoverage=ON . . .` to prepare `coverage.json` report and see from it that the proposed addition will increase branch coverage of line 929 in `AmendmentTable.cpp` from 6/8 to 7/8 .

2024-02-07 22:34 UTC, Bronek approved these changes

2024-02-21 21:15 UTC, ximinez commented
@mvadari Is this ready to merge?

2024-02-21 21:55 UTC, mvadari commented
> @mvadari Is this ready to merge?

@ximinez with Bronek's ✅ , yep - I think it was just waiting on the 2.1 release.

2024-02-21 23:10 UTC, ximinez commented
Proposed commit message:

```
feat: add user version of `feature` RPC (#4781)

* hides potentially sensitive data
* uses same formatting as admin RPC
```

2024-02-21 23:16 UTC, mvadari commented
> Proposed commit message:
> 
> ```
> feat: add user version of `feature` RPC (#4781)
> 
> * hides potentially sensitive data
> * uses same formatting as admin RPC
> ```

nit: I'd switch the order of the bullets
```
feat: add user version of `feature` RPC (#4781)

* uses same formatting as admin RPC
* hides potentially sensitive data
```

2024-02-28 23:28 UTC, intelliot commented
From my perspective, @ximinez or @seelabs are welcome to merge this. (no big rush though)

2024-03-05 21:43 UTC, merged