Proposed 2.1.0
XRPLF/rippled pull request #4920
Opened 2024-02-16 21:44 UTC by seelabs

2024-02-16 22:43 UTC, intelliot approved these changes
Target release date: Feb 20, 2024

2024-02-17 06:03 UTC, kennyzlei approved these changes

2024-02-20 22:35 UTC, ximinez requested changes
Looks like `RELEASENOTES.md` needs to be updated.

2024-02-21 00:59 UTC, ximinez approved these changes
I added the release notes. No code changes, so no need to wait for CI.

2024-02-21 01:25 UTC, merged