Fix compatibility with Conan 2.x
XRPLF/rippled pull request #5001
Opened 2024-04-23 14:29 UTC by thejohnfreeman

This PR makes a few small changes to `conanfile.py` that make it work with Conan 2.x in my basic testing. I don't think we should recommend 2.x yet. It requires a small change to the `conan export` instructions, and the `conan profile update` instructions are completely invalid. Builders will have to manually edit their profiles to make changes. 1.x support is unaffected.

Closes #4926, #4990

2024-04-24 17:21 UTC, ximinez requested changes
Partial review

2024-04-24 17:21 UTC, ximinez commented on BUILD.md
> +- [Conan 1.60](https://conan.io/downloads.html)
If you're making this change, but still not recommending >=2.0, maybe add a note to that effect here.

2024-04-25 15:24 UTC, Bronek approved these changes
I tested it on
* MacOS with apple-clang-15 (and with `-DBOOST_ASIO_DISABLE_CONCEPTS` workaround, moved to both `buildenv` and `runenv`)
* Linux with clang-17 (also with workaround `-DBOOST_ASIO_DISABLE_CONCEPTS` workaround)
* Linux with gcc-12

... and it worked on all three without a hitch. I tried only `Debug` , but I've also run unit tests just to be sure.

One comment for possible documentation improvement, this aside this is brilliant - thank you !

2024-04-25 17:09 UTC, thejohnfreeman commented on BUILD.md
> +
We should be encouraging the `conf.tools` settings. Environment variables are frowned upon, but sometimes a necessary backup depending on (a) the Conan version and (b) the Conan generator. As Conan matures, environment variables will stop working and everything will use `conf.tools`. That said, I'll add a comment about environments in Conan 2.x.

2024-04-25 19:14 UTC, ximinez approved these changes
Partial approval: Thank you for adding the footnote. I'm just adding this to remove the pending change request.

2024-05-02 17:14 UTC, legleux approved these changes
Building `rippled` is fine but building the package has issues which I'm sure are expected at the moment

2024-05-06 16:01 UTC, seelabs approved these changes

2024-06-11 17:26 UTC, merged