Update OpenView.cpp
XRPLF/rippled pull request #5019
Opened 2024-05-20 05:09 UTC by jeffreysmooths

## High Level Overview of Change

### Context of Change

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Performance (increase or change in throughput and/or latency)
- [ ] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [ ] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

2024-05-20 13:33 UTC, exunda requested changes
Recommend you close this change request because its garbage

2024-05-20 13:33 UTC, exunda commented on src/ripple/ledger/impl/OpenView.cpp
> +        return true ; me z
Obviously incorrect change

2024-05-20 13:33 UTC, exunda commented on src/ripple/ledger/impl/OpenView.cpp
> +    info_.validated = true;
Obviously incorrect change

2024-05-21 10:27 UTC, danielCalbonero12345 approved these changes

2024-05-21 20:48 UTC, mvadari commented
Closing this PR as it appears accidental

2024-05-21 20:48 UTC, closed without merging