Pr/retry rpc
XRPLF/rippled pull request #5120
Opened 2024-09-06 18:46 UTC by ximinez

## High Level Overview of Change

Retries failed RPC connection timeouts up to 3 times, unless the test is expecting a timeout. Geared toward fixing MacOS test run failures. 

Also remove an orphaned free function: `getAccounts`.

### Context of Change

MacOS CI jobs have been failing spuriously for a while due to timeouts. This seems to resolve the issue.

### Type of Change

- [X] Tests (you added tests for code that already exists, or your new feature included in this PR)

### API Impact

None

2024-09-06 19:10 UTC, HowardHinnant approved these changes
Thank you!

2024-09-09 09:29 UTC, Bronek approved these changes
LGTM

2024-09-11 09:16 UTC, thejohnfreeman requested changes

2024-09-11 09:16 UTC, thejohnfreeman commented on src/test/jtx/impl/Env.cpp
> +            int retries = 3;
```suggestion
            // We shouldn't need to retry, but it fixes the test on macOS for the moment.
            int retries = 3;
```

2024-09-11 09:19 UTC, thejohnfreeman approved these changes

2024-09-11 10:29 UTC, merged