refactor: add `rpcName` to `LEDGER_ENTRY` macro
XRPLF/rippled pull request #5202
Opened 2024-11-22 21:12 UTC by mvadari

## High Level Overview of Change

The new `LEDGER_ENTRY` macro now takes one additional parameter, `rpcName`. This makes it easier to avoid missing including the new field in `jss.h` and to the list of `account_objects`/`ledger_data` filters.

### Context of Change

Prevent easy bugs.

### Type of Change

- [x] Refactor (non-breaking change that only restructures code)

### API Impact

No change to the user.

## Test Plan
All tests still pass.

2024-12-02 15:38 UTC, mvadari commented
Looks like Windows tests are failing. I'm not sure how to resolve that.

2024-12-04 01:06 UTC, thejohnfreeman requested changes

2024-12-04 01:06 UTC, thejohnfreeman commented on include/xrpl/protocol/jss.h
> +#pragma pop_macro("LEDGER_ENTRY_DUPLICATE")
The pattern we're going with is this:

```
#pragma push_macro
#undef
#pragma push_macro
#undef

#define
#define

#include

#undef
#pragma pop_macro
#undef
#pragma pop_macro
```

@Bronek feels more strongly about this pattern, but I agree it should be consistent everywhere.

2024-12-04 01:06 UTC, thejohnfreeman commented on src/xrpld/rpc/detail/RPCHelpers.cpp
> +
I think you need to add a definition for `LEDGER_ENTRY_DUPLICATE` here (and accompanying `#undef`, `#pragma push_macro`, `#pragma pop_macro`).

2024-12-04 01:17 UTC, thejohnfreeman commented
The Windows error is this [bug](https://stackoverflow.com/questions/5134523/msvc-doesnt-expand-va-args-correctly). Below is the fix, to go in `ledger_entries.macro`:

```cpp
#ifndef LEDGER_ENTRY_DUPLICATE
#define EXPAND(x) x
#define LEDGER_ENTRY_DUPLICATE(...) EXPAND(LEDGER_ENTRY(__VA_ARGS__))
#endif

...

#undef EXPAND
#undef LEDGER_ENTRY_DUPLICATE
```

2024-12-05 04:44 UTC, thejohnfreeman commented on include/xrpl/protocol/detail/ledger_entries.macro
> +#define EXPAND(x) x
Consider adding a comment here linking the Stack Overflow answer.

2024-12-05 04:45 UTC, thejohnfreeman approved these changes

2024-12-05 18:49 UTC, mvadari commented on include/xrpl/protocol/detail/ledger_entries.macro
> +#define EXPAND(x) x
Added in [d67b7bf](https://github.com/XRPLF/rippled/pull/5202/commits/d67b7bf138937061075f27373987d633e937c89c)

2024-12-31 20:28 UTC, godexsoft approved these changes

2025-01-02 15:21 UTC, mvadari commented
@bthomee this PR is ready to merge

2025-01-02 16:35 UTC, bthomee approved these changes

2025-01-02 16:54 UTC, merged